JAVASRC = Balanced.java  RefStack.java Node.java
SOURCES = README Makefile $(JAVASRC)
MAINCLASS = Balanced
CLASSES = Balanced.class RefStack.class Node.class
JARFILE = Balanced.jar

all: $(JARFILE)

$(JARFILE): $(CLASSES)
	echo Main-class: $(MAINCLASS) > Manifest
	jar cvfm $(JARFILE) Manifest $(CLASSES)
	rm Manifest
	chmod +x $(JARFILE)

$(CLASSES): $(JAVASRC)
	javac -Xlint $(JAVASRC)
clean:
	rm $(CLASSES) $(JARFILE)
